name: Deploy Power Tune to Safaricom

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_prod.txt
    
    - name: Test application
      run: |
        python -c "from app import app; print('✅ App imports successfully')"
    
    - name: Deploy to Safaricom Server
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/powertune
          git pull origin main
          source venv/bin/activate
          pip install -r requirements_prod.txt
          sudo systemctl restart powertune
          sudo systemctl restart nginx
          echo "✅ Deployment completed successfully!"
